name: CI Production
on:
  push:
    tags:
      - 'v0.1.*'
      - 'v0.0.*'

jobs:
  build-code:
    uses: ./.github/workflows/build_code.yaml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV }}

  build-docker:
    uses: ./.github/workflows/build_docker.yaml
    needs: [ build-code ]
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV }}

  release-cli:
    needs: [ build-docker ]
    uses: ./.github/workflows/release_asset.yaml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV }}